name: "Lint PR commit message"

on:
  pull_request_target:
    types:
    - opened
    - edited
    - synchronize

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: amannn/action-semantic-pull-request@v3.4.1
      with:
        validateSingleCommit: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload strace artifacts
      uses: actions/upload-artifact@v4
      with:
        name: strace-logs-${{ github.job }}-${{ matrix.flavor || 'lint' }}-${{ github.run_id }}-${{ github.run_attempt }}-${{ strategy.job-index || 0 }}
        path: /home/runner/strace_logs/
